import type { LucideIcon } from 'lucide-react'
import {
  Activity, AlertCircle, Archive, ArrowDownRight, ArrowLeft, ArrowRight, ArrowUpRight, BarChart3, Bell, BadgeCheck, BookOpen, Bot, Building2, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, CircleDollarSign, CircleHelp, ClipboardCheck, Clock3, Cloud, Code2, Command, Copy, Database, Download, Ellipsis, FileArchive, FileBarChart2, FileCheck2, FileClock, FileCode2, FileSpreadsheet, FileText, Filter, FlaskConical, FolderOpen, Gauge, GitBranch, Globe2, Grid2X2, History, Inbox, Info, KeyRound, LayoutDashboard, Lightbulb, LifeBuoy, Link2, ListFilter, LockKeyhole, LogOut, Mail, Menu, MessageCircle, MessageSquare, Mic2, MoreHorizontal, Network, PanelLeftClose, PanelLeftOpen, Paperclip, Pause, PenLine, Play, Plus, RefreshCw, Search, Send, Settings2, Shield, ShieldAlert, ShieldCheck, SlidersHorizontal, Sparkles, SquarePen, Tag, Terminal, ThumbsDown, ThumbsUp, Timer, Trash2, TriangleAlert, UploadCloud, UserRound, UsersRound, Workflow, X, Zap
} from 'lucide-react'

const icons: Record<string, LucideIcon> = {
  activity: Activity, alert: AlertCircle, archive: Archive, 'arrow-down-right': ArrowDownRight, 'arrow-left': ArrowLeft, 'arrow-right': ArrowRight, 'arrow-up-right': ArrowUpRight, 'bar-chart': BarChart3, bell: Bell, 'badge-check': BadgeCheck, book: BookOpen, bot: Bot, building: Building2, calendar: CalendarDays, check: Check, 'check-circle': CheckCircle2, 'chevron-down': ChevronDown, 'chevron-left': ChevronLeft, 'chevron-right': ChevronRight, 'circle-dollar-sign': CircleDollarSign, help: CircleHelp, 'clipboard-check': ClipboardCheck, clock: Clock3, cloud: Cloud, code: Code2, command: Command, copy: Copy, database: Database, download: Download, ellipsis: Ellipsis, 'file-archive': FileArchive, 'file-bar-chart': FileBarChart2, 'file-check': FileCheck2, 'file-clock': FileClock, 'file-code': FileCode2, 'file-spreadsheet': FileSpreadsheet, 'file-text': FileText, filter: Filter, flask: FlaskConical, folder: FolderOpen, gauge: Gauge, branch: GitBranch, 'git-branch': GitBranch, globe: Globe2, grid: Grid2X2, history: History, inbox: Inbox, info: Info, key: KeyRound, dashboard: LayoutDashboard, lightbulb: Lightbulb, support: LifeBuoy, link: Link2, list: ListFilter, lock: LockKeyhole, logout: LogOut, mail: Mail, menu: Menu, message: MessageCircle, 'message-square': MessageSquare, mic: Mic2, more: MoreHorizontal, network: Network, 'panel-left-close': PanelLeftClose, 'panel-left-open': PanelLeftOpen, paperclip: Paperclip, pause: Pause, edit: PenLine, play: Play, plus: Plus, refresh: RefreshCw, search: Search, send: Send, settings: Settings2, shield: Shield, 'shield-alert': ShieldAlert, 'shield-check': ShieldCheck, sliders: SlidersHorizontal, sparkles: Sparkles, compose: SquarePen, tag: Tag, terminal: Terminal, 'thumbs-down': ThumbsDown, 'thumbs-up': ThumbsUp, timer: Timer, trash: Trash2, 'triangle-alert': TriangleAlert, upload: UploadCloud, user: UserRound, users: UsersRound, workflow: Workflow, x: X, zap: Zap,
}

export function Icon({ name, size = 18, strokeWidth = 1.8, className, ...props }: { name: string; size?: number; strokeWidth?: number; className?: string } & Omit<React.SVGProps<SVGSVGElement>, 'name'>) {
  const Component = icons[name] ?? CircleHelp
  return <Component size={size} strokeWidth={strokeWidth} className={className} {...props} />
}
