export type Classification = 'Public' | 'Internal' | 'Confidential' | 'Restricted' | 'Highly Restricted'

export interface SessionUser {
  tenantId: string
  userId: string
  sessionId: string
  email: string
  displayName: string
  departmentId: string
  roles: string[]
  permissions: string[]
  requestId: string
}

export interface Metric { label: string; value: string; detail: string; trend: number; tone: 'violet' | 'teal' | 'amber' | 'blue' | 'rose'; icon: string }
export interface SearchResult { id: string; kind: 'document' | 'meeting' | 'agent' | 'workflow' | 'audit'; title: string; description: string; resource: string; classification?: Classification; updatedAt: string; score: number }
export interface SearchResponse { query: string; items: SearchResult[]; total: number }

// P2-E unified search
export type UnifiedSearchMode = 'auto' | 'lexical' | 'semantic' | 'hybrid' | 'graph'
export type UnifiedSearchKind = 'document' | 'meeting' | 'agent' | 'workflow' | 'graph' | 'memory'
export interface SearchScoreFactors { semantic: number | null; lexical: number | null; phrase: number | null; title: number | null; authority: number | null; freshness: number | null; conflictPenalty: number; total: number; matchedTerms: string[] }
export interface UnifiedSearchItem { id: string; kind: UnifiedSearchKind; title: string; snippet: string; resource: string; classification: Classification; updatedAt: string; score: number; documentId?: string; section?: string | null; page?: number | null; provenance?: string; factors: SearchScoreFactors }
export interface SearchFacets { kinds: Record<string, number>; classifications: Record<string, number> }
export interface UnifiedSearchResponse { query: string; requestedMode: UnifiedSearchMode; resolvedMode: Exclude<UnifiedSearchMode, 'auto'>; items: UnifiedSearchItem[]; total: number; offset: number; limit: number; facets: SearchFacets; tookMs: number; embeddingCacheHit: boolean; degradedReason?: string; warnings: string[] }
export interface SearchSuggestion { text: string; source: 'document' | 'graph' | 'meeting' | 'recent' }
export interface ProactiveAlert { id: string; title: string; description: string; severity: 'high' | 'medium' | 'low'; kind: 'expiry' | 'conflict' | 'gap' | 'trend' | 'approval'; source: string; actionLabel: string; createdAt: string }
export interface ReadinessCheck { id: string; category: 'Identity' | 'Knowledge' | 'AI' | 'Security' | 'Operations'; label: string; status: 'ready' | 'warning' | 'blocked'; detail: string; actionLabel: string }
export interface ReadinessSnapshot { status: 'READY' | 'READY_WITH_WARNINGS' | 'NOT_READY'; organizationName: string; checks: ReadinessCheck[]; nextSteps: string[]; evaluatedAt: string }
export interface ProductHealthDimension { key: string; label: string; value: number | null; kind: 'measured' | 'estimated' | 'not_measured'; detail: string; trend: number | null }
export interface ProductHealthSnapshot { overall: number | null; status: 'healthy' | 'watch' | 'not_measured'; dimensions: ProductHealthDimension[]; evaluatedAt: string }
export interface ValueMetrics { period: string; measured: Array<{ key: string; label: string; value: string; detail: string }>; estimated: Array<{ key: string; label: string; value: string; detail: string }>; unavailable: Array<{ key: string; label: string; detail: string }> }
export interface DashboardOverview {
  organization: { id: string; name: string; plan: string; memberCount: number; documentCount: number; healthScore: number; aiAccuracy: number; verifiedResponses: number }
  metrics: Metric[]
  healthFactors: Array<{ label: string; value: number; tone: 'violet' | 'teal' | 'amber' | 'blue' }>
  reviewDue: number
  activity: ActivityItem[]
  risks: RiskItem[]
  conflicts: Array<{ id: string; title: string; description: string; documents: Array<{ label: string; value: string }>; status: string }>
  knowledgeGaps: Array<{ id: string; question: string; frequency: number; department: string; impact: string; status: string }>
  agentNetwork: Array<{ id: string; name: string; category: string; status: string; usage: number; color: string }>
  departments: Array<{ name: string; queries: number; trust: number; color: string }>
  lastUpdated: string
}
export interface ActivityItem { id: string; type: 'ai' | 'document' | 'agent' | 'workflow' | 'security' | 'meeting'; title: string; description: string; actor: string; timestamp: string; status: 'success' | 'info' | 'warning' | 'danger' }
export interface RiskItem { id: string; title: string; description: string; severity: 'high' | 'medium' | 'low'; owner: string; due: string; kind: 'conflict' | 'stale' | 'gap' | 'security' }
export interface DocumentRecord { id: string; title: string; source: string; owner: string; department: string; classification: Classification; status: 'ready' | 'processing' | 'review' | 'failed'; pages: number; chunks: number; version: string; updatedAt: string; nextReview: string; trust: number; fileSize: string; fileType: string; tags: string[] }
export interface AgentRecord { id: string; name: string; initials: string; description: string; category: string; status: 'published' | 'testing' | 'draft' | 'disabled'; version: string; model: string; knowledgeSources: number; toolCount: number; monthlyQueries: number; trust: number; accent: string; owner: string; lastUpdated: string }
export interface MeetingRecord { id: string; title: string; month: string; day: string; meta: string; status: string; tone: 'success' | 'info' | 'warning'; icon: string }
export interface WorkflowRecord { id: string; name: string; description: string; status: 'active' | 'draft' | 'paused'; trigger: string; lastRun: string; successRate: number; executions: number; requiresApproval: boolean; steps: number }
export interface AuditEvent { id: string; eventType: string; description: string; actor: string; resource: string; timestamp: string; outcome: 'allowed' | 'blocked' | 'completed' | 'pending'; severity: 'low' | 'medium' | 'high' }
export interface AnalyticsSnapshot { period: string; summary: Array<{ label: string; value: string; detail: string; trend: number; icon: string }>; aiUsage: Array<{ label: string; value: number }>; departmentUsage: Array<{ label: string; value: number; color: string }>; trustTrend: Array<{ label: string; value: number }>; modelUsage: Array<{ model: string; requests: number; tokens: string; cost: string; share: number }>; valueMetrics: ValueMetrics }
export interface EvaluationSnapshot { runId: string; datasetVersion: string; completedAt: string; totalCases: number; passedCases: number; score: number; groundedness: number; citationCoverage: number; refusalAccuracy: number; clarificationAccuracy: number; averageLatencyMs: number; retrievalMetrics: { recallAt5: number; precisionAt5: number; mrr: number; ndcgAt5: number }; cases: Array<{ id: string; category: string; difficulty: string; passed: boolean; latencyMs: number; intent: string; responseType: string; trustLabel: string; citationCount: number; structured: boolean; sourceIds: string[]; failures: string[] }>; categories: Array<{ label: string; passed: number; total: number; score: number }> }
export interface ModelProfile { id: string; provider: string; tier: 'fast' | 'balanced' | 'frontier'; capabilities: string[]; contextWindow: number; maxOutput: number; inputUsdPerMillion: number | null; outputUsdPerMillion: number | null; recommendedFor: string[]; source: string }
export interface ModelScorecard { modelId: string; provider: string; tier: string; status: 'measured' | 'not_measured'; weightedScore: number | null; measurements: Record<string, number> | null; inputUsdPerMillion: number | null; outputUsdPerMillion: number | null; recommendation: string }
export interface PolicyRecord { id: string; name: string; category: 'AI policy' | 'Data policy' | 'Approval' | 'Retention' | 'Security'; description: string; status: 'enforced' | 'draft' | 'review'; updatedAt: string; scope: string; owner: string }
export interface AdminConfigurationRecord { id: string; title: string; detail: string; status?: string }
export interface AdminUser { id: string; name: string; email: string; initials: string; department: string; role: string; status: 'active' | 'invited' | 'suspended'; lastActive: string; risk: 'low' | 'medium' | 'high' }
export interface Citation { id: string; documentId: string; title: string; section: string; page?: number; owner: string; updatedAt: string; relevance: number; classification: Classification; excerpt: string }
export interface TrustAssessment { overall: number | null; retrieval: number | null; grounding: number | null; policy: number | null; label: 'Verified' | 'Needs review' | 'Insufficient evidence'; warnings: string[] }
export interface AIResponseRecord { id: string; question: string; answer: string; agent: string; agentVersion: string; model: string; provider: string; promptVersion: string; intent: string; responseType: string; sourceMode: string; route: { model: string; provider: string; reasoningEffort: string; rationale: string; fallbackModels: string[] }; delegation: { supervisor: string; agents: string[]; parallel: boolean; tasks: string[] }; progress: string[]; followUps: string[]; structuredData?: { title: string; columns: string[]; rows: Array<string[]>; sourceLabel: string; asOf: string }; createdAt: string; latencyMs: number; tokenUsage: { input: number; output: number }; trust: TrustAssessment; citations: Citation[] }
export interface AIAskResult { response: AIResponseRecord; conversationId: string }

export type LearningDataStatus = 'measured' | 'synthetic' | 'estimated' | 'projected' | 'not_measured'
export interface LearningMetric { key: string; label: string; value: number | null; unit: string; status: LearningDataStatus; provenance: string; sampleSize: number | null; trend: number | null; detail: string }
export interface ProductRecommendation { id: string; title: string; category: string; evidence: string[]; reason: string; expectedBenefit: string; confidence: number; suggestedOwner: string; priority: 'P0' | 'P1' | 'P2'; status: 'proposed' | 'accepted' | 'deferred' | 'rejected'; governance: string }
export interface OperatingSignal { id: string; signalType: string; title: string; summary: string; purpose: string; sourceRef: string; sourceMode: string; classification: string; owner: string; severity: 'low' | 'medium' | 'high' | 'critical'; state: 'normal' | 'unusual' | 'important' | 'critical'; status: 'open' | 'acknowledged' | 'resolved'; priorityScore: number; confidence: number; affectedUsers: number | null; businessImpact: number; urgency: number; risk: number; detectedAt: string; expiresAt: string | null; evidence: string[]; recommendedAction: string; provenance: string }
export interface OperatingContext { id: string; signalId: string; subjectScope: string; task: string; sourceMode: string; permissionBoundary: string; selectedEvidence: string[]; liveState: string[]; relationships: string[]; assumptions: string[]; unknowns: string[]; assembledAt: string; provenance: string }
export interface OperatingDecision { id: string; title: string; context: string; evidence: string[]; alternatives: string[]; recommendation: string; decision: string | null; decisionMaker: string | null; proposedWorkflowId?: string; owner: string; risk: 'low' | 'medium' | 'high' | 'critical'; classification: string; status: string; createdAt: string; approvedAt: string | null; action?: { workflowId: string; executionId?: string; status: string; message: string }; outcomeId?: string; provenance: string }
export interface OperatingOutcomeMetric { key: string; label: string; value: number | null; unit: string }
export interface OperatingOutcome { id: string; decisionId: string; expected: string; actual: string; before: OperatingOutcomeMetric[]; after: OperatingOutcomeMetric[]; status: string; evidence: string[]; measuredAt: string; provenance: string }
export interface OrganizationalMemoryRecord { id: string; memoryType: string; title: string; summary: string; owner: string; sourceRef: string; date: string; authority: string; classification: string; permissions: string[]; retention: string; version: string; status: string; provenance: string }
export interface OperatingProcess { id: string; name: string; department: string; currentState: string; owner: string; cycleTimeHours: number | null; waitTimeHours: number | null; reworkRate: number | null; failureRate: number | null; escalations: number | null; manualSteps: number | null; automationRate: number | null; bottleneck: string; recommendation: string; provenance: string }
export interface OperatingInsight { id: string; title: string; summary: string; evidence: string[]; owner: string; severity: 'low' | 'medium' | 'high' | 'critical'; confidence: number; recommendedAction: string; provenance: string }
export interface OperatingIntelligenceSnapshot { version: string; generatedAt: string; scope: { tenantId: string; environment: string; notice: string }; operatingModel: { stages: string[]; principle: string; failureIsolation: string }; metrics: Array<{ key: string; label: string; value: number | null; unit: string; status: string; detail: string }>; detection: { normal: number; unusual: number; important: number; critical: number; status: string; detail: string }; signals: OperatingSignal[]; contexts: OperatingContext[]; decisions: OperatingDecision[]; outcomes: OperatingOutcome[]; memory: OrganizationalMemoryRecord[]; processes: OperatingProcess[]; risks: OperatingInsight[]; opportunities: OperatingInsight[]; quality: { detectionPrecision: number | null; recommendationQuality: number | null; evidenceQuality: number | null; falsePositiveRate: number | null; falseNegativeRate: number | null; decisionUsefulness: number | null; outcomeSuccess: number | null; status: string; detail: string }; reliability: { coreProductAvailable: boolean; intelligenceFailureIsolated: boolean; status: string; detail: string } }
export interface ValueIntelligenceMetric { key: string; label: string; value: number | null; unit: string; status: 'measured' | 'estimated' | 'projected' | 'not_measured'; confidence: 'HIGH' | 'MEDIUM' | 'LOW' | 'UNKNOWN'; attribution: string; sampleSize: number | null; detail: string }
export interface ValueEvent { id: string; tenantId: string; userId: string; department: string; kind: string; title: string; linkedResource: string; evidence: string[]; status: string; confidence: string; attribution: string; minutesSaved: number | null; valueUsd: number | null; costUsd: number | null; before: Array<{ key: string; label: string; value: number | null; unit: string }>; after: Array<{ key: string; label: string; value: number | null; unit: string }>; createdAt: string; provenance: string }
export interface ValueIntelligenceSnapshot { version: string; generatedAt: string; scope: { tenantId: string; environment: string; notice: string }; valueChain: Array<{ stage: string; status: string; evidence: string; nextMeasurement: string }>; scores: { enterpriseValue: ValueIntelligenceMetric; aiRoi: ValueIntelligenceMetric; customerValue: ValueIntelligenceMetric; productHealth: ValueIntelligenceMetric; businessHealth: ValueIntelligenceMetric }; activity: { aiRequests: ValueIntelligenceMetric; successfulAnswers: ValueIntelligenceMetric; valueEvents: ValueIntelligenceMetric; valueConversion: ValueIntelligenceMetric; detail: string }; summary: ValueIntelligenceMetric[]; valueEvents: ValueEvent[]; cost: { inputTokens: number; outputTokens: number; modelCost: ValueIntelligenceMetric; costPerRequest: ValueIntelligenceMetric; costPerSuccessfulOutcome: ValueIntelligenceMetric; costPerWorkflow: ValueIntelligenceMetric; costByDepartment: Array<{ department: string; cost: ValueIntelligenceMetric }>; costByModel: Array<{ model: string; cost: ValueIntelligenceMetric }>; expensiveWorkloads: string[]; detail: string }; featurePortfolio: Array<{ key: string; feature: string; portfolio: string; aiQuality: ValueIntelligenceMetric; businessValue: ValueIntelligenceMetric; usage: ValueIntelligenceMetric; recommendation: string; rationale: string }>; departments: Array<{ department: string; primaryUseCase: string; valueHypothesis: string; metrics: ValueIntelligenceMetric[]; strongestSignal: string; recommendation: string }>; customerHealth: { status: string; segments: Array<{ key: string; label: string; count: number | null; evidence: string }>; detail: string }; competitiveAdvantage: { status: string; differentiator: string; validationQuestions: string[]; comparisons: Array<{ competitor: string; observedStrength: string; SmartCorpEvidence: string }> }; investmentPriorities: Array<{ priority: string; initiative: string; reason: string; expectedValue: string; status: string }>; experiments: Array<{ id: string; hypothesis: string; targetUsers: string; expectedOutcome: string; measurement: string[]; cost: string; duration: string; successCriteria: string[]; failureCriteria: string[]; status: string }>; scenarios: Array<{ id: string; scenario: string; response: string; risk: string; leadingIndicator: string; status: string }>; businessCase: { problem: string; buyer: string; reasonToPay: string; valueReceived: string; costToSmartCorp: string; retention: string; expansion: string; advantageRisk: string } }

export interface ProductLearningSnapshot {
  version: string
  generatedAt: string
  scope: { tenantId: string; environment: string; notice: string }
  pilot: { id: string; name: string; version: string; status: string; syntheticNotice: string; tenantCount: number; syntheticUserCount: number; departments: Array<{ id: string; name: string; mission: string; syntheticUsers: number; sourceCount: number; permissionBoundary: string }>; roles: string[]; personas: Array<{ id: string; name: string; department: string; goal: string; exampleQuestion: string; accessProfile: string }>; knowledgeSources: Array<{ type: string; count: number; examples: string[]; classification: string }>; dataset: { version: string; materializedRecordCount: number; recordTypes: string[]; notice: string; sampleRecords: Array<{ id: string; type: string; title: string; department: string; classification: string; owner: string; sourceSystem: string; lastReviewed: string; content: string; synthetic: true }> }; workflowCount: number; agentCount: number; permissionMatrix: Array<{ profile: string; allows: string[]; denies: string[]; testIntent: string }>; securityChecks: Array<{ id: string; scenario: string; expected: string; observed: string; status: string; evidence: string }>; journeys: Array<{ id: string; name: string; stages: string[]; acceptanceGate: string; status: string }>; resetPolicy: string }
  benchmark: { version: string; totalTasks: number; executedTasks: number; notMeasuredTasks: number; executionMode: string; qualityScore: LearningMetric; categoryCoverage: Array<{ category: string; catalogued: number; executedInPhase6: number; status: string; note: string }>; regressionGate: { status: string; baselineVersion: string; rule: string; detail: string } }
  qualityScores: LearningMetric[]
  qualityRubric: LearningMetric[]
  failures: Array<{ category: string; observedCount: number; developmentObservedCount: number; productionObservedCount: number; syntheticPilotCount: number; trend: string; examples: string[]; owner: string; action: string }>
  knowledge: { score: LearningMetric; components: Array<{ key: string; label: string; value: number; status: LearningDataStatus; detail: string }>; gaps: Array<{ id: string; question: string; frequency: number; department: string; impact: string; suggestedOwner: string; status: string; provenance: LearningDataStatus }>; conflicts: Array<{ id: string; title: string; sources: string[]; affectedUsers: string; authority: string; status: string; provenance: LearningDataStatus }>; freshness: Array<{ document: string; owner: string; lastReviewed: string; nextReview: string; priority: string; provenance: LearningDataStatus }> }
  agents: { status: LearningDataStatus; rows: Array<{ id: string; name: string; invocations: number | null; successRate: number | null; latencyMs: number | null; costUsd: number | null; humanEscalationRate: number | null; feedbackCount: number; detail: string }> }
  workflows: { status: LearningDataStatus; rows: Array<{ id: string; name: string; executions: number; successRate: number; approvalRate: number; bottleneck: string; automationOpportunity: string }>; repeatedPatterns: Array<{ pattern: string; frequency: number; recommendation: string; confidence: number }> }
  userBehavior: { status: LearningDataStatus; syntheticCohort: { users: number; departments: number; journeys: number }; signals: Array<{ key: string; label: string; value: number | null; detail: string; status: LearningDataStatus }>; reformulations: Array<{ questionFamily: string; sequence: string[]; likelyCause: string; nextInvestigation: string }> }
  feedback: { status: LearningDataStatus; totals: Record<string, number>; improvementSignals: Array<{ signal: string; count: number; likelyCause: string; owner: string }> }
  modelPerformance: Array<{ model: string; provider: string; status: LearningDataStatus; accuracy: number | null; latencyMs: number | null; costPerRequestUsd: number | null; reasoningQuality: number | null; toolCalling: number | null; structuredOutput: number | null; multimodal: number | null; longContext: number | null; failureRate: number | null; recommendation: string }>
  cost: { status: LearningDataStatus; requests: number; inputTokens: number; outputTokens: number; modeledCostUsd: number | null; costPerSuccessfulOutcomeUsd: number | null; byDepartment: Array<{ department: string; requests: number; costUsd: number | null }>; byModel: Array<{ model: string; requests: number; costUsd: number | null }>; expensiveWorkloads: Array<{ workload: string; reason: string; recommendation: string }>; detail: string }
  experiments: Array<{ id: string; key: string; hypothesis: string; variants: string[]; primaryMetric: string; guardrails: string[]; status: string; approvalRequired: boolean; result: string }>
  recommendations: ProductRecommendation[]
  observability: { status: LearningDataStatus; traceStages: string[]; redactions: string[]; sinks: string[]; gaps: string[] }
  departments: Array<{ department: string; topQuestions: string[]; usage: LearningMetric; knowledgeCoverage: LearningMetric; automationOpportunity: LearningMetric; trustRisk: string; permissionNote: string }>
  executiveInsights: Array<{ title: string; detail: string; evidence: string; priority: 'P0' | 'P1' | 'P2'; provenance: LearningDataStatus }>
  businessValue: { status: LearningDataStatus; metrics: Array<{ key: string; label: string; value: number | null; unit: string; status: LearningDataStatus; detail: string }>; outcomeLinks: string[] }
  productHealth: { overall: number | null; status: string; scoreType: string; dimensions: LearningMetric[]; detail: string }
  proactiveSignals: Array<{ id: string; signal: string; severity: 'high' | 'medium' | 'low'; evidence: string; recipient: string; dedupeWindow: string; status: string }>
  scale: { status: string; assumptions: Array<{ key: string; value: string; detail: string }>; scenarios: Array<{ users: number; activeUsers: number; aiRequestsPerDay: number; peakAiRequestsPerSecond: number; concurrentModelCalls: number; searchRequestsPerSecond: number; documents: number; vectorRows: number; auditEventsPerDay: number; storageGbPerMonth: number; queueJobsPerDay: number; bottlenecks: string[]; status: string }>; nextValidation: string[] }
  pilotSuccess: { status: string; criteria: Array<{ key: string; label: string; target: string; result: string; status: string; evidence: string }>; graduationRule: string }
  scaleReadiness: { classification: string; evidence: string[]; blockers: string[]; nextDecision: string }
  topPainPoints: Array<{ title: string; detail: string; evidence: string; priority: 'P0' | 'P1' | 'P2'; provenance: LearningDataStatus }>
  topOpportunities: Array<{ title: string; detail: string; evidence: string; priority: 'P0' | 'P1' | 'P2'; provenance: LearningDataStatus }>
  topRisks: Array<{ title: string; detail: string; evidence: string; priority: 'P0' | 'P1' | 'P2'; provenance: LearningDataStatus }>
  nextPriorities: ProductRecommendation[]
}
